### ISSUE TITLE
AJAX search  with data-handler issue

### ISSUE THREAD

**Issue by pittss** [octobercms/ajax#10]
If look ui documentation https://octobercms.com/docs/ui/select (section: AJAX search)

`<select class="form-control custom-select"
    data-handler="onGetOptions"
    data-minimum-input-length="2"
    data-ajax--delay="300"
    data-request-data="foo: 'bar'"></select>`

Ajax request does not taking `data-request-data`

OctoberCMS Version: 3.0.59

**Comment by daftspunk** [comment]
Thanks for finding this. It should be fixed in v3.0.60+. Keep an eye on the changelog for updates: https://octobercms.com/changelog
