### ISSUE TITLE
Input name not escaped correctly

### ISSUE THREAD

**Issue by acasar** [octobercms/ajax#13]
The "=" character in input name is not escaped correctly.

If we have a simple form like this:
```html
<form data-request="onTest">
    <input type="text" name="models[test=1]" value="value" />
    <input type="submit">
</form>
```

In the old framework this is submitted correctly:

**Name:** models[test=1]
**Value:** value

![image](https://user-images.githubusercontent.com/6329543/180777244-053ced72-4cbe-4104-a382-9e4f682d0674.png)

But in the new framework it's submitted incorrectly:

**Name:** models[test
**Value:** 1]=value

![image](https://user-images.githubusercontent.com/6329543/180777345-e102fba5-3089-4c70-9f11-6cf7842034e4.png)

**Comment by samgeorges** [comment]
Thanks for finding this. It will be fixed in the next patch release of v3 (>= v3.0.63)
