### ISSUE TITLE
Turbo router and target property

### ISSUE THREAD

**Issue by acasar** [octobercms/ajax#15]
I noticed that the turbo router disables itself if a target attribute is present on an anchor element regardless of its value. This represents an issue, since we often use the following pattern to output links:

```twig
<a href="{{ link }}" target="{{ link | link_target }}">Button</a>
```

The ``link_target`` filter returns either ``_self`` or ``_blank`` depending on whether the url belongs to the application or not. Unfortunately that disables turbo router on such links in either case. I think that the turbo router should still apply itself to links with either ``_self`` or empty target property unless it's specifically disabled by ``data-turbo="false"``.

**Comment by daftspunk** [comment]
Sure, makes sense. 

344925dad906be5f7d3ffb6bfb08ff231604debf
