### ISSUE TITLE
Turbo cache http header?

### ISSUE THREAD

**Issue by acasar** [octobercms/ajax#18]
Is there any way to add some http header to the pjax request when a re-cache is requested (i.e. after the page has been resolved from the turbo cache and a new request is made)?

The reason we need this is that we are using some javascript to lazy load images, where ``<img data-src>`` is replaced with ``<img src>``. But when the page is rendered from the turbo cache, the lazy loaded images are already resolved before the new request comes in and causes all images to momentarily disappear and re-appear again. This could easily be fixed by letting the server know when a re-cache is  requested so we can format the resulting html accordingly (replace all ``data-src`` attributes with ``src`` before returning the response).

**Comment by daftspunk** [comment]
We might be able to add something like this to the header:

```
X-PJAX = 1 // Loaded normally
X-PJAX = 2 // Loaded with a preceding snapshot 
```

However, Laravel's `Request::pjax()` only checks for its presence (`== true`), which also needs to be enhanced. It should lead us to think about alternative ideas...

Generally speaking, a cached page and an uncached page should behave consistently. This means the animations should occur with or without the cache state. To prevent the flashing, you can detect the presence of a snapshot using CSS and hide the images or pause them from animating:

```
html[data-turbo-preview] {
    // pause/hide animated images
}
```

Then when this `data-turbo-preview` attribute is removed, the images animate again. This keeps it consistent.

It would be ideal if you could work with this solution. That way, we avoid making things too complicated.

**Comment by acasar** [comment]
We tried pausing the lazy-loader while ``[data-turbo-preview]`` is present, but it delays displaying the images until the pjax request is finished, which somehow defeats the purpose of using turbo cache.

I was thinking about adding the possibility to modify the request header ourselves, maybe something like this:

```js
addEventListener('page:request', function(xhr) {
    if (document.documentElement.hasAttribute('data-turbo-preview')) {
        xhr.setRequestHeader("Turbo-Recache-Requested", "1");
    }
});
```

The alternative would be to add a hook where we can manipulate the pjax response before it replaces the snapshot, which would also ensure cache consistency.

```js
addEventListener('page:before-replace', function(html) {
    // manipulate html before it replaces the cached version
});
```

Would something like this be possible?

**Comment by daftspunk** [comment]
Hi @acasar 

The `ajax:request-start` event could be used here...

```js
addEventListener('ajax:request-start', function(event) {
    const { xhr } = event.detail;

    // Not attached yet... (see below)
    if (document.documentElement.hasAttribute('data-turbo-preview')) {
        xhr.setRequestHeader("Turbo-Recache-Requested", "1");
    }
});
```

However, the main problem with this approach is the load order. The workflow makes the request and then renders the snapshot, so checking the `data-turbo-preview` attribute will never yield any results.

You've made a clear case for a `Request::pjaxCached()` method. After some investigation, I can't see any other simple way around it.

Related commits

- bee119eca4dc0e4cca7c334824111fd105bd9a8f
- https://github.com/octobercms/library/commit/47367eaff42bef1b350abf19158ae2de01a0cb5c
- https://github.com/octobercms/docs/commit/eb7be78744254cc2b029b97b37aae907bb6d9f63

**Comment by acasar** [comment]
Thanks, that looks great 👍
