### ISSUE TITLE
Turbo ignoring data-turbo-permanent

### ISSUE THREAD

**Issue by FlusherDock1** [octobercms/ajax#2]
1. Installed octobercms ajax module via npm
2. add require('octobercms') to js file
3. Turbo already loaded, and working great
4. Add data-turbo-permanent attribute to header, so it won't update every page load
5. Turbo updates header anyway

**Comment by daftspunk** [comment]
Hi @FlusherDock1 

Please paste the HTML that you're using and confirm that the element also has a valid id attribute? eg: `id="something"`

Thanks!

**Comment by FlusherDock1** [comment]
> Please paste the HTML that you're using and confirm that the element also has a valid id attribute? eg: id="something"

```
<header data-turbo-permanent>
    // ...
</header>
```

Just whole header without any attributes

**Comment by daftspunk** [comment]
It needs an `id` as per the docs

```
<header id="header" data-turbo-permanent>
```
