### ISSUE TITLE
Preserve scroll on turbo request

### ISSUE THREAD

**Issue by acasar** [octobercms/ajax#21]
Is there any way to easily preserve the scroll position on turbo request? Right now every turbo request scrolls to top which is ok for most use cases. But preserving the scroll position would be very useful for situations where we have links that basically act like filters (e.g. links to categories in a blog). It would give the effect of reloading the list of articles with ajax while in the background still acting like a full refresh.

Ideally it should be possible to achieve this by adding a data attribute to the ``<a href>`` element (e.g. ``data-turbo-preserve-scroll``). Is something like that already possible or at least achievable with some additional javascript?

**Comment by daftspunk** [comment]
Makes sense.

```
<a href="/" data-turbo-no-scroll>Filter</a>
```

"No scroll" doesn't preserve the scroll, per se, it keeps the current scroll position. "Preserve scroll" would be remembering the last scroll position for every URL seen and restoring it on a subsequent visit.

---

Added here: https://github.com/octobercms/ajax/commit/8d26a97ac7352f3d5a8e5470e5648660b0a3a258

Documented here: https://github.com/octobercms/docs/commit/589eb0e94cd6f52569ca010a3221f76b0955cfe3

**Comment by acasar** [comment]
Thanks! This is exactly what we were looking for. 👍
