### ISSUE TITLE
Hot Controls doesn't work with Typescript

### ISSUE THREAD

**Issue by FlusherDock1** [octobercms/ajax#24]
This new feature, https://docs.octobercms.com/3.x/cms/ajax/hot-controls.html#global-events, cannot be used with ts, since it doesn't exist in `.d.ts` file.

**Comment by daftspunk** [comment]
Made an attempt at this here: 3c8c31d1fdc18d3d1b1c7f045ec06eb0fa7149c3

We may need @jacobdekeizer to confirm
