### ISSUE TITLE
Value not sent in data-request for textarea

### ISSUE THREAD

**Issue by vdlp-mw** [octobercms/ajax#25]
We ran into an issue where calling `$(el).request()` on a textarea does not contain the value of the textarea in the request anymore. Not entirely sure when this broke, but our best guess is after upgrading from OC2.X to OC3.X.

If the `<textarea>` is replaced with `<input />` the value is posted correctly. 

This does not work:
```
<textarea name="comment" id="comment" cols="30" rows="10" 
    data-request="onUpdateComment"></textarea>

$('#comment').request();
```

But this does work: 
```
<input name="comment" id="comment" 
    data-request="onUpdateComment" />

$('#comment').request();
```

When looking through the code I suspect the issue can be found here: https://github.com/octobercms/ajax/blob/main/src/request/data.js#L58-L60. The value is not added if element type is not `input` or `select`. I think `textarea` should be added here. This would be consistent with the `isElementInput` method used here: https://github.com/octobercms/ajax/blob/main/src/extras/attach-loader.js#L117-L119

**Comment by samgeorges** [comment]
Thank you for the detailed report! This fix will be included in the next patch release.
