### ISSUE TITLE
Passive event listeners

### ISSUE THREAD

**Issue by Metallizzer** [octobercms/ajax#27]
Hello.

Can you add please ability to pass options to local Hot Controls listeners as in native js addEventListener https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
Sometimes we need to pass parameters {passive: true} for wheel, mousewheel, touchstart and touchmove events or something else

**Comment by daftspunk** [comment]
Hi, can you give provide an example?

**Comment by Metallizzer** [comment]
Working native js example
```js
var element = document.querySelector(".some-element");

element.addEventListener('touchmove', callback, {
    passive: true
});
```

```js
oc.registerControl(
    "some-element",
    class extends oc.ControlBase {
        connect() {
            this.listen("touchmove", this.onMove); // We need to be able to pass parameters {passive: true} to this listener
        }

        onMove(e) {
            // move element
        }
    }
);
```
Without {passive: true} options chrome add warnings "[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952"

![image](https://github.com/octobercms/ajax/assets/691719/52772c66-918d-41ba-bb0b-493883966efd)

**Comment by daftspunk** [comment]
Interesting, I didn't realise Chrome warns for this.

Here is a workaround for now...

```js

oc.registerControl(
    "some-element",
    class extends oc.ControlBase {
        connect() {
            this.element.addEventListener("touchmove", this.proxy(this.onMove), { passive: true });
        }

        disconnect() {
            this.element.removeEventListener("touchmove", this.proxy(this.onMove));
        }

        onMove(e) {
            // move element
        }
    }
);
```

**Comment by Metallizzer** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners

> Setting the passive option to true — as shown in the following example — enables performance optimizations that can dramatically improve the performance of an application.

**Comment by Metallizzer** [comment]
> Interesting, I didn't realise Chrome warns for this.
> 
> Here is a workaround for now...
> 
> ```js
> oc.registerControl(
>     "some-element",
>     class extends oc.ControlBase {
>         connect() {
>             this.element.addEventListener("touchmove", this.proxy(this.onMove), { passive: true });
>         }
> 
>         disconnect() {
>             this.element.removeEventListener("touchmove", this.proxy(this.onMove));
>         }
> 
>         onMove(e) {
>             // move element
>         }
>     }
> );
> ```

Thanks, I'll try this for now

**Comment by Metallizzer** [comment]
@daftspunk Please note that there may be other parameters not only "passive"

**Comment by daftspunk** [comment]
Noted. It may be more complex than passing the parameters. The [event handler code](https://github.com/octobercms/ajax/blob/main/src/util/events.js) allows delegation to sub-components. Passive could also be applied by default for some events and then opt-out if "preventDefault" is needed.

Related discussions

- https://github.com/jquery/jquery/issues/2871
- https://github.com/twbs/bootstrap/issues/32070

**Comment by daftspunk** [comment]
As per your original suggestion, support for passing options has been added in 3d64f1b76db00bdb9a12366c291cee2c4a641a42

After considering the points made in the related discussions, this ajax library seems unaffected by jQuery's concerns. Bootstrap uses only a few events affected by passive events (low priority for them). So we should be safe to proxy the options to the internals.

Thanks!

**Comment by Metallizzer** [comment]
Thanks @daftspunk

**Comment by Metallizzer** [comment]
Hello @daftspunk, just got back to this issue, 3d64f1b only makes changes to the Events class, but how do we use that in the ControlBase listen method?

**Comment by daftspunk** [comment]
Good catch, d695fca8c2b8dcaebd63972a3b290f74da131ffa should fix it...

**Comment by Metallizzer** [comment]
Thanks @daftspunk
