### ISSUE TITLE
No option for toggling off ProgressBar

### ISSUE THREAD

**Issue by FlusherDock1** [octobercms/ajax#3]
I have several xhr requests that fires every time page loads.
![Снимок экрана 2022-06-16 в 18 52 58](https://user-images.githubusercontent.com/20070837/174113142-74cab85a-1903-40fc-9abc-f2d470f8459d.png)
 
But if it is combined with turbo, the progress bar start to be annoying, by flashing on every request.

**Comment by daftspunk** [comment]
Hey @FlusherDock1 

Looks like this was a bug, the bar is enabled by default when using extra features but you can disable with

```
oc.ajax('onAjax', { progressBar: false });
```

Related
- 6979581936a8d311d72c7c220820bb6350bf0159
- https://github.com/octobercms/docs/commit/e4221631c67256318713761f5e944e6b2d0dca5c

**Comment by FlusherDock1** [comment]
> https://github.com/octobercms/docs/commit/e4221631c67256318713761f5e944e6b2d0dca5c

Is there an option to globally turn off progressBar? My frontend has spinners in every button that triggers xhr request, so i don't need additional information about request loading

**Comment by daftspunk** [comment]
> Is there an option to globally turn off progressBar? 

Yes, you can hide with CSS or ajax:setup event via `event.detail.context.options.progressBar = false`

**Comment by samgeorges** [comment]
@FlusherDock1 I've added [a test for this here](https://github.com/daftspunk/test-theme/commit/c0ca3601be33aef9d22fb9817705f76052916970) and it appears to be working. Are you on the latest version?

**Comment by FlusherDock1** [comment]
> @FlusherDock1 I've added [a test for this here](https://github.com/daftspunk/test-theme/commit/c0ca3601be33aef9d22fb9817705f76052916970) and it appears to be working. Are you on the latest version?

Try adding sleep not to AJAX Request but to onInit(), so the page will load longer. than visit it with turbo

**Comment by samgeorges** [comment]
Sorry, I misunderstood. This only disables for AJAX. I will investigate how to disable it for PJAX too.

**Comment by samgeorges** [comment]
Ok this is ready - ebcfc48cec94a6442475adc18856a16e0a8f9b7f

Disable in JS with `oc.AjaxTurbo.setProgressBarVisible(false)`

Disable in CSS with `.oc-progress-bar.is-turbo { display: none }`
