### ISSUE TITLE
Using SelectorObserver instead of ScopeObserver

### ISSUE THREAD

**Issue by Metallizzer** [octobercms/ajax#36]
Hello @daftspunk 

Is there any way to initialize oc.registerControl for use with the SelectorObserver class instead of ScopeObserver?
Or maybe there is some workaround for this?

**Comment by daftspunk** [comment]
Hi @Metallizzer 

Can you share more detail about what you want to achieve?

**Comment by Metallizzer** [comment]
I would like to be able to register controls using css selectors, not just via data-control
```javascript
oc.registerControl(
    ".css-selector",
    class extends oc.ControlBase {
        // ...
    }
);
```
In the source codes there is a [SelectorObserver](https://github.com/octobercms/ajax/blob/main/src/observe/mutation/selector-observer.js) class, so I thought that maybe there is such an opportunity

**Comment by Metallizzer** [comment]
Maybe something like this for example

```javascript
oc.registerControl(
    ".css-selector",
    class extends oc.ControlBase {
        // Here we could override the default
        static useObserver() {
            return 'SelectorObserver';
        }
    }
);
```

**Comment by daftspunk** [comment]
Keep in mind that `data-control` is an important identifier of a hot control, and there is JS logic attached. i.e. When the developer sees this tag, they know to look for the associated `oc.registerControl` code to understand how it functions.

Could you please describe in more detail the problem of adding `data-control=""` to the HTML element?

**Comment by Metallizzer** [comment]
Okay, I get your point. We will use data-control="". Thank you.

**Comment by daftspunk** [comment]
No problem, we initially had this idea too, but couldn't find the reason to implement it. So it is classed as an intentional design decision.

Thanks!

**Comment by daftspunk** [comment]
For anyone who stumbles across this, here is a solution: https://talk.octobercms.com/t/custom-selectors-with-hot-controls/1883
