### ISSUE TITLE
TypeScript typings issue

### ISSUE THREAD

**Issue by SamBrishes** [octobercms/ajax#37]
Hello,

I noticed the following type issues while using your library:

1. [`RequestOptions.files`](https://github.com/octobercms/ajax/blob/main/types/index.d.ts#L28C5-L28C10) is declared as a `FormData` object type, but only used as a boolean identifier [here](https://github.com/octobercms/ajax/blob/main/src/request/request.js#L52). The [default value](https://github.com/octobercms/ajax/blob/main/src/request/request.js#L27) is a boolean as well.

2. The [`ajax`](https://github.com/octobercms/ajax/blob/main/types/index.d.ts#L153) function declaration is supposed to return `void`, but actually returns the [`Deferred`](https://github.com/octobercms/ajax/blob/main/src/request/request.js#L80C21-L80C29) instance .

3. The above may applies also to the [`request`](https://github.com/octobercms/ajax/blob/main/types/index.d.ts#L154) function declaration. I haven't used the function yet, but in a short console test I got a `Deferred` object in return as well.

4. The [`parseJson()`](https://github.com/octobercms/ajax/blob/main/types/index.d.ts#L155) function declaration is supposed to return `void`, but according [to the code](https://github.com/octobercms/ajax/blob/main/src/util/json-parser.js#L27) you probably get all types back that `JSON.parse` itself supports (`boolean | number | string | null | object | Array`).

~ Sam.

**Comment by daftspunk** [comment]
Hey @SamBrishes 

Thanks for reviewing this. We don't use TypeScript internally and it was a user contribution, you are welcome to update the file directly via a Pull Request. Otherwise, we will try to address each point soon.

**Comment by daftspunk** [comment]
Cleaning up issues.
