### ISSUE TITLE
Turbo need one more event

### ISSUE THREAD

**Issue by FlusherDock1** [octobercms/ajax#4]
Turbo doesn't have an event that triggers if page was loaded via non-turbo visit. Or I didn't find it :)

Example:

I have a mini-cart in header, that I want to load on first non-turbo visit. On this mini-cart i have `data-turbo-permanent` attribute, so it won't reload on every turbo-visit.

**Comment by daftspunk** [comment]
You can use `Request::pjax()` to determine if the request came from the turbo router.

**Comment by daftspunk** [comment]
We've added this to Twig for next release:

```
<!-- If request is PJAX, don't show the mini cart in the header -->
{% if not this.request.pjax %}
    ... mini cart ...
{% endif %}
```
