### ISSUE TITLE
Progress bar element is added outside of body on AJAX request

### ISSUE THREAD

**Issue by markoKodric** [octobercms/ajax#42]
Progress bar element is added outside of body when AJAX/turbo request is triggered, so the HTML is invalid.

Could it be fixed so that element is added as a child to a body element?

**Comment by daftspunk** [comment]
Hi @markoKodric 

The progress bar element exists outside the body since the body contents can be swapped by AJAX/PJAX. As a result, the progress bar is preserved during the transition.

I hope this helps!
