### ISSUE TITLE
data-request does not work correctly

### ISSUE THREAD

**Issue by pittss** [octobercms/ajax#5]
If put data-request on select with css class `custom-select`, it does not trigger ajax request.

`<?= Form::select('period', range(0, 12), 1, ['class' => 'form-control custom-select', 'data-request' => 'onTest']) ?>`

October CMS version: v3.0.50

**Comment by daftspunk** [comment]
Hey @pittss. Thanks for finding this.

It is actually a problem with the select control. Pushed a fix for v3.0.51+, keep an eye on the changelog for the release: https://octobercms.com/changelog
