### ISSUE TITLE
DOM not updating if referenced by attribute

### ISSUE THREAD

**Issue by acasar** [octobercms/ajax#7]
If we have the following markup:

```html
<div data-param="test"></div>
<script>$.request('onTest');</script>
```

And the following handler:

```php
function onTest() {
    return ['[data-param="test"]' => 'response'];    
}
```

We would expect ``response`` to be injected into the ``[data-param="test"]`` element, which worked ok in the old framework. However in the new framework, the response is not injected.

**Comment by daftspunk** [comment]
Ok we will need to add "[" as an approved leading character. 

The new framework is more strict and currently only allows "#" and "." and this is how it can tell between a DOM update and ordinary data. 

The documentation originally only allowed "#" and everything else was unofficially supported. Need to draw the line somewhere...

**Comment by acasar** [comment]
Thanks for a quick response. Adding a class in front of the attribute selector indeed works as expected. And yes, we were very creative in using some of the framework's features, that just comes with a big team 🙂 So if something is a wontfix just let me know and we'll find a workaround.

**Comment by daftspunk** [comment]
No problem, we will stick with only allowing `#` (single) and `.` (multi) under normal circumstances. However, we've also added a new `=` (custom) prefix that lets you use any selector:

```
// Replace [data-param=test]
function onTest() {
    return ['=[data-param="test"]' => 'response'];    
}

// Replace all divs
function onTest() {
    return ['=div' => 'response'];    
}
```

Related:
- efa1cc416fabd48a9f3d847b180f344dbc284989
- https://github.com/octobercms/docs/commit/32db6a1740434824d760d0f39d2878b74f9a208c

**Comment by acasar** [comment]
Thanks! Having an option to do ``=`` is great 👍
