### ISSUE TITLE
Multilingual repeater does not accept & character any more

### ISSUE THREAD

**Issue by acasar** [octobercms/ajax#8]
I found a strange bug where we can't use the & character in multilingual repeaters any more. I tested with https://github.com/octobercms/test-plugin (of course we also need the Translate plugin installed with at least 2 languages added).

Then we go to the url ``october/test/countries/update/2`` where we have a translatable repeater in a builder mode. We add a Textarea with the following content:

![image](https://user-images.githubusercontent.com/6329543/174491808-97bbc330-8d31-4feb-a77e-e8f6ed467958.png)

When we try changing the language of the repeater in October 3.0.44 we get an ajax request with the following payload:

![image](https://user-images.githubusercontent.com/6329543/174491950-986a5cd4-cd99-4692-ad4b-f56ef78c33c8.png)

But when we try to do the same in the latest version of October, we get this:

![image](https://user-images.githubusercontent.com/6329543/174492062-1b751f99-7a3a-42ac-9050-d10a50007965.png)

When we switch back to the original locale, everything after the & character is trimmed. Therefore I assume this is an issue with the new ajax framework not escaping the & character properly in repeaters. In my tests it works fine with other field types.

**Comment by daftspunk** [comment]
Thanks, fixed by a86ade808f6abb1025a6ffc6a4c6177f8fa89b87
