### ISSUE TITLE
Regression in 3.0.53

### ISSUE THREAD

**Issue by acasar** [octobercms/ajax#9]
Unfortunately, another issue has been introduced in 3.0.53. I assume it's related to recent changes to Ajax plugin.

I have extended [Pages plugin](https://github.com/rainlab/pages-plugin) with custom repeater (builder):

```php
Event::listen('backend.form.extendFields', function($widget) {
    if (!$widget->model instanceof \RainLab\Pages\Classes\Page) return;
    if (!isset($widget->secondaryTabs['fields']['markup'])) return;

    $widget->addSecondaryTabFields([
        'viewBag[builder]' => [
            'type' => 'repeater',
            'displayMode' => 'builder',
            'tab'  => 'Custom builder',
            'groups' => [
                'textarea' => [
                    'name' => 'Textarea',
                    'icon' => 'icon-file-text-o',
                    'fields' => [
                        'content' => [
                            'label' => 'Text Content',
                            'type' => 'textarea',
                            'size' => 'large',
                        ]
                    ]
                ]
            ]
        ]
    ]);
});
``` 

Until 3.0.51 this woked fine, however in 3.0.53 I get the following error when trying to add a new "Textarea" item:
![image](https://user-images.githubusercontent.com/6329543/174665037-1478bcab-d07b-4ed9-b462-5f923ed8293b.png)

The issue is that most of the data is missing from AJAX request:
![image](https://user-images.githubusercontent.com/6329543/174663303-328535d2-8665-4890-9849-ff4f564d6659.png)
In 3.0.51 the request was generated correctly:
![image](https://user-images.githubusercontent.com/6329543/174664540-60f234af-d11d-4d14-8eec-b9802e852332.png)

**Comment by daftspunk** [comment]
This is a race condition in the core with the repeater. [Fixed in core](https://github.com/octobercms/october-private/commit/d14bbeb149c2db09601981bd22bba265c46f4f97) with hash d14bbeb149c2db09601981bd22bba265c46f4f97 and will be available v3.0.54
